$schema: "../_base/meta.schema.json"
test:
  type: snapshot
fixtures:
  base: books-table.js
snapshots:
  share: true
  sources:
    udt::definitions:
      types:
        - member
    stdout::matches:
      regex: ^(|\{"status":\{"ok":1\}\})$
    stderr::matches:
      regex: ^$
