package com.dtsx.docs.lib;

import com.dtsx.docs.config.VerifierCtx;
import lombok.Cleanup;
import lombok.NonNull;
import lombok.val;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.FileTime;
import java.time.Instant;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.*;
import java.util.function.Consumer;
import java.util.function.Function;

import static com.dtsx.docs.lib.ColorUtils.stripAnsi;

/// **Note: Docs for this class were generated by AI**
///
/// Centralized logging utility that handles console output with optional loading spinners and automatic log file generation.
///
/// All output is accumulated in memory and written to `.docs_tests_temp/logs/<timestamp>.astra.log` at the end.
/// Keeps only the 10 most recent log files.
///
/// Supports:
/// - Colored output via `@|color text|@` syntax (see [ColorUtils])
/// - Loading spinners that pause during log output
/// - Automatic ANSI stripping for log files
///
/// **Adapted from Astra CLI.**
public class CliLogger {
    private static final List<String> accumulated = Collections.synchronizedList(new ArrayList<>());

    private static Optional<LoadingSpinner> globalSpinner = Optional.empty();
    private static boolean spinnerEnabled;

    /// Enables or disables the loading spinner.
    ///
    /// Controlled by `--spinner`/`--no-spinner` flags or `SPINNER` env var (default: true).
    /// When disabled, loading messages are printed directly instead of showing a spinner.
    public static void setSpinnerEnabled(boolean spinnerEnabled) {
        CliLogger.spinnerEnabled = spinnerEnabled;
    }

    /// Prints to stdout without a newline.
    public static void print(String... msg) {
        log(String.join("", msg), System.out);
    }

    /// Prints to stdout with a newline.
    public static void println(String... msg) {
        log(String.join("", msg) + System.lineSeparator(), System.out);
    }

    /// Prints an error message to stdout (not stderr) without a newline.
    public static void error(String... msg) {
        log(String.join("", msg), System.out);
    }

    /// Prints an error message to stderr with a newline.
    public static void errorln(String... msg) {
        log(String.join("", msg) + System.lineSeparator(), System.err);
    }

    /// Logs a debug message (only to log file, not console).
    ///
    /// Prefixed with `[DEBUG]` in the log file.
    public static void debug(String... msg) {
        log("[DEBUG] " + String.join("", msg), null);
    }

    /// Executes a function while showing a loading spinner with a message.
    ///
    /// The spinner can be updated mid-execution via the consumer parameter.
    /// Automatically pauses the spinner when other log methods are called.
    ///
    /// Example:
    /// ```java
    /// val result = loading("Installing dependencies...", (updateMsg) -> {
    ///     installNpm();
    ///     updateMsg.accept("Installing Python packages...");
    ///     installPip();
    ///     return "done";
    /// });
    /// ```
    ///
    /// @param initialMsg the initial spinner message (supports color formatting)
    /// @param supplier function that performs work and optionally updates the message
    /// @return the result from the supplier
    public static <T> T loading(@NonNull String initialMsg, Function<Consumer<String>, T> supplier) {
        val formattedMsg = ColorUtils.format(initialMsg);

        accumulated.add("[LOADING:STARTED] " + formattedMsg);

        val isFirstLoading = globalSpinner.isEmpty();

        if (isFirstLoading && spinnerEnabled) {
            globalSpinner = Optional.of(LoadingSpinner.start(formattedMsg));
        }

        try {
            return supplier.apply((msg) -> {
                globalSpinner.ifPresent(s -> s.updateMessage(ColorUtils.format(msg)));
                accumulated.add("[LOADING:UPDATED] " + msg);
            });
        } finally {
            if (isFirstLoading) {
                globalSpinner.ifPresent(LoadingSpinner::stop);
                globalSpinner = Optional.empty();
            }
            accumulated.add("[LOADING:DONE] " + formattedMsg);
        }
    }

    /// Logs an exception message (only to log file, not console).
    ///
    /// Prefixed with `[ERROR]` in the log file.
    public static void exception(String... msg) {
        log("[ERROR] " + String.join("", msg), System.err);
    }

    /// Logs an exception with a message and returns the exception for rethrowing.
    ///
    /// Example:
    /// ```java
    /// throw exception("Failed to parse file", new IOException("bad format"));
    /// ```
    public static <E extends Throwable> E exception(String msg, E e) {
        exception(msg);
        return exception(e);
    }

    /// Logs an exception's stack trace and returns it for rethrowing.
    ///
    /// Example:
    /// ```java
    /// throw exception(new RuntimeException("oops"));
    /// ```
    public static <E extends Throwable> E exception(E e) {
        exception(captureStackTrace(e));
        return e;
    }

    private static void log(String msg, @Nullable PrintStream ps) {
        val formattedMsg = ColorUtils.format(msg);

        accumulated.add(formattedMsg);

        if (ps == null) {
            return;
        }

        val resume = globalSpinner.map(LoadingSpinner::pause);

        try {
            ps.print(formattedMsg);
            ps.flush();
        } finally {
            resume.ifPresent(Runnable::run);
        }
    }

    /// Writes all accumulated logs to a timestamped file in `.docs_tests_temp/logs/`.
    ///
    /// Called automatically at the end of test execution. Strips ANSI color codes from the output.
    /// Keeps only the 10 most recent log files, deleting older ones.
    ///
    /// Log file format: `yyyy_MM_dd___H_mm_ss.astra.log`
    public static void dumpLogsToFile(VerifierCtx ctx) {
        try {
            val timestamp = DateTimeFormatter.ofPattern("yyyy_MM_dd___H_mm_ss").format(Instant.now().atZone(ZoneId.systemDefault()));
            val sessionLogFile = logsDir(ctx).resolve(timestamp + ".astra.log");

            Files.createDirectories(sessionLogFile.getParent());
            deleteOldLogs(logsDir(ctx));

            @Cleanup val writer = Files.newBufferedWriter(sessionLogFile);

            for (val line : accumulated) {
                writer.write(stripAnsi(line));
                writer.write(System.lineSeparator());
            }
        } catch (Exception _) {}
    }

    private static void deleteOldLogs(Path logsDir) {
        try {
            @Cleanup val logFiles = Files.list(logsDir);

            logFiles
                .sorted(Comparator.<Path, FileTime>comparing((path) -> {
                    try {
                        return Files.getLastModifiedTime(path);
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }).reversed())
                .skip(10)
                .forEach((f) -> {
                    try {
                        Files.delete(f);
                    } catch (Exception e) {
                        exception("Error deleting old log file '", f.toString(), "': ", e.getMessage());
                    }
                });
        } catch (Exception _) {}
    }

    private static String captureStackTrace(Throwable t) {
        val sw = new StringWriter();
        t.printStackTrace(new PrintWriter(sw));
        return sw.toString();
    }

    private static Path logsDir(VerifierCtx ctx) {
        return ctx.tmpFolder().resolve("logs");
    }
}
