package com.dtsx.docs.lib;

import com.dtsx.docs.config.VerifierCtx;
import com.dtsx.docs.runner.SourceCodeReplacer;
import lombok.RequiredArgsConstructor;
import lombok.val;
import org.apache.commons.lang3.ArrayUtils;
import org.jetbrains.annotations.Nullable;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Executors;
import java.util.function.Function;
import java.util.function.Predicate;

import static com.dtsx.docs.lib.ExternalPrograms.ExternalProgramType.*;

/// **Note: Docs for this class were generated by AI**
///
/// Factory for creating [ExternalProgram] instances with command overrides from [VerifierCtx].
///
/// Each program can be overridden via environment variables (e.g., `TSX_COMMAND=npx -y tsx`)
/// or CLI flags (e.g., `-Ctsx='npx -y tsx'`), falling back to sensible defaults.
public class ExternalPrograms {
    /// Returns a tsx executor (default: `npx -y tsx`).
    ///
    /// Used to run JavaScript fixtures and TypeScript test files.
    public static ExternalProgram tsx(VerifierCtx ctx) {
        return get(TSX, ctx);
    }

    /// Returns an npm executor (default: `npm`).
    ///
    /// Used to install dependencies for fixtures and execution environments.
    public static ExternalProgram npm(VerifierCtx ctx) {
        return get(NPM, ctx);
    }

    /// Returns a bash executor (default: `bash`).
    ///
    /// Used to run bash example scripts.
    public static ExternalProgram bash(VerifierCtx ctx) {
        return get(BASH, ctx);
    }

    /// Returns a python executor (default: `python3`).
    ///
    /// Used to run Python example scripts.
    public static ExternalProgram python(VerifierCtx ctx) {
        return get(PYTHON, ctx);
    }

    /// Returns a java executor (default: `java`).
    ///
    /// Used to run compiled Java example classes.
    public static ExternalProgram java(VerifierCtx ctx) {
        return get(JAVA, ctx);
    }

    /// Returns a custom executor with no default command.
    ///
    /// Useful for calling definitely-available scripts (such as `./.gradlew`)
    public static ExternalProgram custom(VerifierCtx ctx) {
        return new ExternalProgram(ctx, "custom", new String[0]);
    }

    private static ExternalProgram get(ExternalProgramType type, VerifierCtx ctx) {
        return new ExternalProgram(ctx, type.name().toLowerCase(), ctx.commandOverrides().getOrDefault(type, type.defaultCommand()));
    }

    /// Enum of external programs with their default commands.
    ///
    /// Each can be overridden via `<NAME>_COMMAND` env var (e.g., `TSX_COMMAND=bun tsx`).
    @RequiredArgsConstructor
    public enum ExternalProgramType {
        TSX("npx -y tsx"),
        NPM("npm"),
        BASH("bash"),
        PYTHON("python3"),
        JAVA("java");

        private final String defaultCommand;

        public String[] defaultCommand() {
            return defaultCommand.split(" ");
        }
    }

    /// Represents a line of output from a program, tagged as stdout or stderr.
    public sealed interface OutputLine { String unwrap(); }
    
    /// A line from stdout.
    public record StdoutLine(String unwrap) implements OutputLine {}
    
    /// A line from stderr.
    public record StderrLine(String unwrap) implements OutputLine {}

    /// Result of running an external program.
    ///
    /// Captures exit code and all output lines (stdout and stderr) in the order they were produced.
    ///
    /// Example:
    /// ```java
    /// val result = tsx.run("script.ts");
    /// if (result.exitCode() != 0) {
    ///     System.err.println(result.stderr());
    /// }
    /// ```
    public record RunResult(int exitCode, List<OutputLine> outputLines) {
        /// Returns only stdout as a single string.
        public String stdout() {
            return buildOutput(StdoutLine.class::isInstance);
        }

        /// Returns only stderr as a single string.
        public String stderr() {
            return buildOutput(StderrLine.class::isInstance);
        }

        /// Returns both stdout and stderr interleaved in the order they were produced.
        public String output() {
            return buildOutput(_ -> true);
        }

        private String buildOutput(Predicate<OutputLine> filter) {
            val sb = new StringBuilder();
            for (val line : outputLines) {
                if (filter.test(line)) {
                    sb.append(line.unwrap());
                }
            }
            return sb.toString();
        }
    }

    /// An external program that can be executed with arguments.
    ///
    /// Automatically injects environment variables (API endpoint, token, etc.) into the process.
    ///
    /// Example:
    /// ```java
    /// val tsx = ExternalPrograms.tsx(ctx);
    /// val result = tsx.run(Path.of("/tmp"), "script.ts", "--verbose");
    /// ```
    public record ExternalProgram(VerifierCtx ctx, String name, String[] cmd) {
        /// Runs the program with the given arguments in the current directory.
        ///
        /// Standard placeholder env vars (`API_ENDPOINT`, `ASTRA_TOKEN`, etc.) are automatically injected.
        ///
        /// @param args command-line arguments to pass to the program
        /// @return the result containing exit code and output
        public RunResult run(String... args) {
            return run(null, args);
        }

        /// Runs the program with the given arguments in a specific directory.
        ///
        /// Standard placeholder env vars (`API_ENDPOINT`, `ASTRA_TOKEN`, etc.) are automatically injected.
        ///
        /// @param workingDir the working directory (null for current directory)
        /// @param args command-line arguments to pass to the program
        /// @return the result containing exit code and output
        public RunResult run(@Nullable Path workingDir, String... args) {
            return run(workingDir, null, args);
        }

        /// Runs the program with the given arguments in a specific directory and environment variables.
        ///
        /// Standard placeholder env vars (`API_ENDPOINT`, `ASTRA_TOKEN`, etc.) are automatically injected.
        ///
        /// @param workingDir the working directory (null for current directory)
        /// @param envVars additional environment variables to set (null for none)
        /// @param args command-line arguments to pass to the program
        /// @return the result containing exit code and output
        public RunResult run(@Nullable Path workingDir, @Nullable Map<String, String> envVars, String... args) {
            try {
                val process = startProcess(workingDir, ArrayUtils.addAll(cmd, args), envVars);

                val outputLines = Collections.synchronizedList(new ArrayList<OutputLine>());

                try (val executor = Executors.newVirtualThreadPerTaskExecutor()) {
                    executor.submit(
                        mkStreamReader(process.getInputStream(), outputLines, StdoutLine::new)
                    );
                    executor.submit(
                        mkStreamReader(process.getErrorStream(), outputLines, StderrLine::new)
                    );
                    return new RunResult(process.waitFor(), outputLines);
                }

            } catch (IOException | InterruptedException e) {
                Thread.currentThread().interrupt();
                return new RunResult(-1, List.of(new StderrLine(e.toString())));
            }
        }

        /// Checks if the program exists and is executable by running `<program> --version`.
        ///
        /// @return true if the program executed successfully, false otherwise
        public boolean exists() {
            try {
                val process = startProcess(null, ArrayUtils.addAll(cmd, "--version"), null);
                val exitCode = process.waitFor();
                return exitCode == 0;
            } catch (IOException | InterruptedException e) {
                Thread.currentThread().interrupt();
                return false;
            }
        }

        /// Returns the environment variable name used to override this program's command.
        ///
        /// For example, `tsx` returns `TSX_COMMAND`, `python` returns `PYTHON_COMMAND`.
        ///
        /// @return the environment variable name (e.g., "TSX_COMMAND")
        public String envVar() {
            return name.toUpperCase() + "_COMMAND";
        }

        private Process startProcess(Path dir, String[] fullCmd, @Nullable Map<String, String> envVars) throws IOException {
            val pb = new ProcessBuilder(fullCmd);

            if (dir != null) {
                pb.directory(dir.toFile());
            }

            pb.environment().putAll(SourceCodeReplacer.mkEnvVars(ctx));

            if (envVars != null) {
                pb.environment().putAll(envVars);
            }

            return pb.start();
        }

        private Runnable mkStreamReader(InputStream stream, List<OutputLine> outputLines, Function<String, OutputLine> mapper) {
            return () -> {
                try (val reader = new BufferedReader(new InputStreamReader(stream))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        outputLines.add(mapper.apply(line + System.lineSeparator()));
                    }
                } catch (IOException ignored) {}
            };
        }

        @Override
        public boolean equals(Object obj) {
            return obj instanceof ExternalProgram other && this.name.equals(other.name);
        }

        @Override
        public int hashCode() {
            return name.hashCode();
        }
    }
}
