$schema: "../../../_base/meta.schema.json"
test:
  type: snapshot
execution: isolated
fixtures:
  base: basic-collection.js
snapshots:
  share: true
  sources:
    stdout::matches:
      regex: .*2.*
    collection::documents:
