$schema: "../../_base/meta.schema.json"
test:
  type: snapshot
fixtures:
  base: basic-collection.js
snapshots:
  share: true
  sources:
    stdout:
      matches: ^(?:\d+|\{"status":\{"count":\d+}})$ # Not deterministic so just any number will do
    stderr:
      matches: ^$
