name: 'test-compilation'
description: 'Runs compilation tests'

inputs:
  clients:
    description: 'Comma-separated list of client drivers to test (e.g., java,typescript,python) or "all" for all clients'
    required: true
  docs-repo:
    description: 'Documentation repository in format [org/repo][#branch] (both the org/repo and branch are optional)'
    required: false
    default: 'riptano/astra-vector-docs#main'
  examples-path:
    description: 'Path to examples folder within the docs repository (defaults to modules/api-reference/examples)'
    required: false
    default: 'modules/api-reference/examples'
  args:
    description: 'Additional arguments to pass to dh'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup dh
      id: setup-dh
      uses: ./actions/_common/setup-dh
      with:
        docs-repo: ${{ inputs.docs-repo }}
        examples-path: ${{ inputs.examples-path }}
        snapshots-path: ${{ inputs.snapshots-path }}
        setup-languages: ${{ inputs.clients }}

    - name: Run compilation tests
      shell: bash
      env:
        CLIENT_DRIVERS: ${{ inputs.clients }}
      run: |
        export ASTRA_TOKEN="dummy-token"
        export API_ENDPOINT="dummy-endpoint"
        
        java --enable-native-access=ALL-UNNAMED \
          -jar "${{ steps.setup-dh.outputs.dh-cli-path }}" \
          test \
          --verify-mode compile_only \
          ${{ inputs.clients }} \
          ${{ inputs.args }}

    - name: Upload failure artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ inputs.client }}-${{ github.run_id }}
        path: |
          logs/
        if-no-files-found: ignore
