$schema: "../../_base/meta.schema.json"
fixtures:
  base: basic-collection.js
snapshots:
  share: true
  sources:
    stdout:
      matches: ^(?:0|\{"status":\{"count":0}})$
    stderr:
      matches: ^$
