$schema: "../../../_base/meta.schema.json"
test:
  type: snapshot
  parallel: true
fixtures:
  base: basic-collection.js
snapshots:
  share:
    bash: false
  sources:
    stderr::matches:
      regex: ^$
