name: 'setup-dh'
description: 'Builds the `dh` cli + installs any required dependencies'

inputs:
  docs-repo:
    description: 'Documentation repository in format [org/repo][@branch] (both the org/repo and branch are optional)'
    required: true
  examples-path:
    description: 'Path to examples folder within the docs repository (defaults to modules/api-reference/examples)'
    required: true
  snapshots-path:
    description: 'Path to snapshots folder within the docs repository (defaults to ${examples-path}/_snapshots)'
    required: true
  setup-languages:
    description: 'Comma-separated list of languages to setup (e.g., java,typescript,python,csharp) or "all" for all languages'
    required: true
  setup-jq:
    description: 'Install jq'
    required: false
    default: 'false'
  script:
    description: 'Script using dh'
    required: true

outputs:
  dh-cli-path:
    description: 'Path to the built dh jar file'
    value: ${{ steps.build-cli.outputs.dh-cli-path }}
  snapshots-folder:
    description: 'Path to the snapshots folder in the docs repo'
    value: ${{ steps.setup-docs.outputs.snapshots-folder }}

runs:
  using: composite
  steps:
    - name: Parse docs-repo input
      id: parse-repo
      shell: bash
      run: |
        REPO_PATH="riptano/astra-vector-docs"
        BRANCH="main"

        REPO_INPUT="${{ inputs.docs-repo }}"
        
        if [[ -n "$REPO_INPUT" ]]; then
          if [[ "$REPO_INPUT" == *"@"* ]]; then
            LEFT="${REPO_INPUT%%@*}"
            RIGHT="${REPO_INPUT#*@}"
        
            [[ -n "$LEFT" ]] && REPO_PATH="$LEFT"
            [[ -n "$RIGHT" ]] && BRANCH="$RIGHT"
          else
            REPO_PATH="$REPO_INPUT"
          fi
        fi
        
        EXAMPLES_PATH="${{ inputs.examples-path }}"

        if [ -n "${{ inputs.snapshots-path }}" ]; then
          SNAPSHOTS_PATH="${{ inputs.snapshots-path }}"
        else
          SNAPSHOTS_PATH="$EXAMPLES_PATH/_snapshots"
        fi
        
        echo "repo-path=$REPO_PATH" >> $GITHUB_OUTPUT
        echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        echo "examples-path=$EXAMPLES_PATH" >> $GITHUB_OUTPUT
        echo "snapshots-path=$SNAPSHOTS_PATH" >> $GITHUB_OUTPUT
        
        echo "Repository: '$REPO_PATH'"
        echo "Branch: '$BRANCH'"
        echo "Examples path: '$EXAMPLES_PATH'"
        echo "Snapshots path: '$SNAPSHOTS_PATH'"

    - name: Print tokens 2
      shell: bash
      run: |
        echo "${{ secrets.DOC_GITHUB_PAT_CROSS_ORG }}" | cut -c1-20
        echo "${{ secrets.DOCS_GITHUB_PAT }}" | cut -c1-20

    - name: Clone docs repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ${{ steps.parse-repo.outputs.examples-path }}
          ${{ steps.parse-repo.outputs.snapshots-path }}
        repository: ${{ steps.parse-repo.outputs.repo-path }}
        ref: ${{ steps.parse-repo.outputs.branch }}
        path: docs-repo
        token: '${{ secrets.DOC_GITHUB_PAT_CROSS_ORG || github.token }}'

    - name: Setup docs repo
      id: setup-docs
      shell: bash
      run: |
        DOCS_PATH="${{ github.workspace }}/docs-repo"
        EXAMPLES_FOLDER="$DOCS_PATH/${{ steps.parse-repo.outputs.examples-path }}"
        SNAPSHOTS_FOLDER="$DOCS_PATH/${{ steps.parse-repo.outputs.snapshots-path }}"
        
        if [ ! -d "$EXAMPLES_FOLDER" ]; then
          echo "ERROR: Examples folder not found: $EXAMPLES_FOLDER"
          exit 1
        fi
        
        echo "EXAMPLES_FOLDER=$EXAMPLES_FOLDER" >> $GITHUB_ENV
        echo "SNAPSHOTS_FOLDER=$SNAPSHOTS_FOLDER" >> $GITHUB_ENV
        
        echo "snapshots-folder=$SNAPSHOTS_FOLDER" >> $GITHUB_OUTPUT
        
        echo "Documentation cloned to: $DOCS_PATH"
        echo "Examples folder: $EXAMPLES_FOLDER"
        echo "Snapshots folder: $SNAPSHOTS_FOLDER"

    # --- java ---
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '25'

    - name: Cache Gradle dependencies
      uses: actions/cache@v5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Verify java
      shell: bash
      run: |
        set -x
        java --version

    # --- typescript ---
    - name: Setup node
      if: inputs.setup-languages == 'all' || contains(inputs.setup-languages, 'typescript')
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Cache npm global packages
      if: inputs.setup-languages == 'all' || contains(inputs.setup-languages, 'typescript')
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-global-

    - name: Verify node
      if: inputs.setup-languages == 'all' || contains(inputs.setup-languages, 'typescript')
      shell: bash
      run: |
        set -x
        node --version
        npm --version
        npx tsx --version

    - name: Setup + verify tsx
      if: inputs.setup-languages == 'all' || contains(inputs.setup-languages, 'typescript')
      shell: bash
      run: |
        set -x
        npm install -g tsx
        npx tsx --version

    # --- python ---
    - name: Setup python
      if: inputs.setup-languages == 'all' || contains(inputs.setup-languages, 'python')
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Verify python
      if: inputs.setup-languages == 'all' || contains(inputs.setup-languages, 'python')
      shell: bash
      run: |
        set -x
        python3 --version

    # --- dotnet ---
    - name: Setup dotnet
      if: inputs.setup-languages == 'all' || contains(inputs.setup-languages, 'csharp')
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Verify dotnet
      if: inputs.setup-languages == 'all' || contains(inputs.setup-languages, 'csharp')
      shell: bash
      run: |
        set -x
        dotnet --version

    # --- jq ---
    - name: Setup + verify jq
      if: inputs.setup-jq == 'true'
      shell: bash
      run: |
        set -x
        sudo apt-get update && sudo apt-get install -y jq
        jq --version

    # --- actually use dh ---
    - name: Use dh
      shell: bash
      run: |
        export SPINNER=false
        source astra-client-docs-tests/scripts/dev-alias.sh
        eval "${{ inputs.script }}"
