$schema: "../../../_base/meta.schema.json"
test:
  type: snapshot
execution: shared
fixtures:
  base: basic-collection.js
snapshots:
  share: true
  sources:
    stdout::jsonify:
      jq-bash: '.data.documents'
